=== dbarbier/privot/lib/src/Base/Func/wrapper.dtd
<?xml encoding="ISO-8859-1"?>

<!-- author : schueller -->
<!-- date   : 2011-06-01 17:59:24 +0200 (Wed, 01 Jun 2011) -->

<!ELEMENT wrapper           (library,external-code) >
<!ELEMENT library           (path,description) >
<!ELEMENT description       (variable-list,function,gradient,hessian) >
<!ELEMENT external-code     (data?,wrap-mode,command,user-prefix?) >
<!ELEMENT data              (file*,framework?) >
<!ELEMENT file              (name?,path,subst?) >
<!ELEMENT framework         (study-id?,study-case?,component-name?) >
<!ELEMENT variable-list     (variable*) >
<!ELEMENT variable          (comment?,unit?,regexp?,format?) >
<!ELEMENT function          (#PCDATA) >
<!ELEMENT gradient          (#PCDATA) >
<!ELEMENT hessian           (#PCDATA) >
<!ELEMENT name              (#PCDATA) >
<!ELEMENT path              (#PCDATA) >
<!ELEMENT subst             (#PCDATA) >
<!ELEMENT regexp            (#PCDATA) >
<!ELEMENT format            (#PCDATA) >
<!ELEMENT unit              (#PCDATA) >
<!ELEMENT comment           (#PCDATA) >
<!ELEMENT study-id          (#PCDATA) >
<!ELEMENT study-case        (#PCDATA) >
<!ELEMENT user-prefix       (#PCDATA) >
<!ELEMENT component-name    (#PCDATA) >
<!ELEMENT wrap-mode         (in-data-transfer,out-data-transfer) >
<!ELEMENT command           (#PCDATA) >
<!ELEMENT in-data-transfer  (#PCDATA) >
<!ELEMENT out-data-transfer (#PCDATA) >


<!ATTLIST wrapper
version NMTOKEN #IMPLIED>

<!ATTLIST file
id ID #REQUIRED
type (in|out) #REQUIRED>

<!ATTLIST variable
id ID #REQUIRED
type (in|out) #REQUIRED
computed-gradient (yes|no) #IMPLIED>

<!ATTLIST wrap-mode
type (static-link|dynamic-link|fork) #REQUIRED
state (shared|specific) #IMPLIED>

<!ATTLIST in-data-transfer
mode (files|pipe|arguments|socket|corba) #REQUIRED>

<!ATTLIST out-data-transfer
mode (files|pipe|arguments|socket|corba) #REQUIRED>

<!ATTLIST function
provided (yes|no) #REQUIRED>

<!ATTLIST gradient
provided (yes|no) #REQUIRED>

<!ATTLIST hessian
provided (yes|no) #REQUIRED>

=== dbarbier/privot/lib/test/TestCompositionRight.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE wrapper SYSTEM "wrapper.dtd">
<wrapper>
  <library>
    <path>TestCompositionRight.so</path>
    <description>
      <variable-list>
        <variable id="x1" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x2" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x3" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x4" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="y1" type="out">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="y2" type="out">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
      </variable-list>
      <function provided="yes">TestCompositionRight</function>
      <gradient provided="yes">TestCompositionRight</gradient>
      <hessian provided="yes">TestCompositionRight</hessian>
    </description>
  </library>
  <external-code>
    <data>
    </data>
    <wrap-mode type="static-link">
      <in-data-transfer mode="arguments" />
      <out-data-transfer mode="arguments" />
    </wrap-mode>
    <command>
    </command>
  </external-code>
</wrapper>

=== dbarbier/privot/lib/test/poutre_threads.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE wrapper SYSTEM "wrapper.dtd">
<!-- author : dutka -->
<!-- date   : 2008-06-26 13:50:17 +0200 (Thu, 26 Jun 2008) -->

<wrapper>
  <library>

    <!-- The path of the shared object -->
    <path>poutre_threads.so</path>



    <!-- This section describes all exchanges data between the wrapper and the platform -->
    <description>

      <!-- Those variables are substituted in the files above -->
      <!-- The order of variables is the order of the arguments of the function -->
      <variable-list>

        <!-- The definition of a variable -->
        <variable id="E" type="in">
          <comment>meanYoungModulus</comment>
          <unit>Pascal</unit>
          <regexp>E=.*</regexp>
          <format>E=%10.5g</format>
        </variable>

        <!-- The definition of a variable -->
        <variable id="F" type="in">
          <comment>LoadForce</comment>
          <unit>Newton</unit>
          <regexp>F=.*</regexp>
          <format>F=%10.5g</format>
        </variable>
      
        <!-- The definition of a variable -->
        <variable id="L" type="in">
          <comment>BeamLength</comment>
          <unit>Meter</unit>
          <regexp>L=[0-9]+\.[0-9]* *m</regexp>
          <format>L=%8.4f</format>
        </variable>
      
        <!-- The definition of a variable -->
        <variable id="I" type="in">
          <comment>SectionInertia</comment>
          <unit>Meter^4</unit>
          <regexp>I=.*</regexp>
          <format>I=%10.5g</format>
        </variable>

        <!-- The definition of a variable -->
        <variable id="d" type="out">
          <comment>Deviation</comment>
          <unit>Meter</unit>
          <regexp>d=.*</regexp>
          <format>d=%10.5g</format>
        </variable>

      </variable-list>
      


      <!-- The function that we try to execute through the wrapper -->
      <function provided="yes">compute_deviation</function>

      <!-- the gradient is  defined  -->
      <gradient provided="no" />

      <!--  the hessian is  defined  -->
      <hessian provided="no" />

    </description>


  </library>

  <external-code>
    <!-- Those data are external to the platform (input files, etc.)-->
    <data>
    </data>

    <wrap-mode type="static-link">
      <in-data-transfer mode="arguments" />
      <out-data-transfer mode="arguments" />
    </wrap-mode>

    <command>
    </command>
  </external-code>

</wrapper>

=== dbarbier/privot/lib/test/TestStrongMaximumTestDimension10.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE wrapper SYSTEM "wrapper.dtd">
<wrapper>
  <library>
    <path>TestStrongMaximumTestDimension10.so</path>
    <description>
      <variable-list>
        <variable id="x1" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x2" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x3" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x4" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x5" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x6" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x7" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x8" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x9" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x10" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="y1" type="out">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
      </variable-list>
      <function provided="yes">TestDim10</function>
      <gradient provided="no" />
      <hessian provided="no" />
    </description>
  </library>
  <external-code>
    <data>
    </data>
    <wrap-mode type="static-link">
      <in-data-transfer mode="arguments" />
      <out-data-transfer mode="arguments" />
    </wrap-mode>
    <command>
    </command>
  </external-code>
</wrapper>

=== dbarbier/privot/lib/test/poutre_fullspeed.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE wrapper SYSTEM "wrapper.dtd">
<!-- author : dutka -->
<!-- date   : 2010-09-14 16:35:33 +0200 (Tue, 14 Sep 2010) -->

<wrapper>
  <library>

    <!-- The path of the shared object -->
    <path>poutre_fullspeed.so</path>



    <!-- This section describes all exchanges data between the wrapper and the platform -->
    <description>

      <!-- Those variables are substituted in the files above -->
      <!-- The order of variables is the order of the arguments of the function -->
      <variable-list>

        <!-- The definition of a variable -->
        <variable id="E" type="in" />
        <variable id="F" type="in" />
        <variable id="L" type="in" />
        <variable id="I" type="in" />


        <!-- The definition of a variable -->
        <variable id="d" type="out" />

      </variable-list>
      


      <!-- The function that we try to execute through the wrapper -->
      <function provided="yes">compute_deviation</function>

      <!-- the gradient is  defined  -->
      <gradient provided="no"></gradient>

      <!--  the hessian is  defined  -->
      <hessian provided="no"></hessian>

    </description>


  </library>

  <external-code>
    <!-- Those data are external to the platform (input files, etc.)-->
    <data></data>

    <wrap-mode type="static-link" state="shared">
      <in-data-transfer mode="arguments" />
      <out-data-transfer mode="arguments" />
    </wrap-mode>

    <command># no command</command>

    <user-prefix>poutreComputeDeviation</user-prefix>

  </external-code>

</wrapper>

=== dbarbier/privot/lib/test/TestResponseSurface.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE wrapper SYSTEM "wrapper.dtd">
<wrapper>
  <library>
    <path>TestResponseSurface.so</path>
    <description>
      <variable-list>
        <variable id="x1" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x2" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="y1" type="out">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="y2" type="out">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="y3" type="out">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
      </variable-list>
      <function provided="yes">TestResponseSurface</function>
      <gradient provided="yes">TestResponseSurface</gradient>
      <hessian provided="yes">TestResponseSurface</hessian>
    </description>
  </library>
  <external-code>
    <data>
    </data>
    <wrap-mode type="static-link">
      <in-data-transfer mode="arguments" />
      <out-data-transfer mode="arguments" />
    </wrap-mode>
    <command>
    </command>
  </external-code>
 </wrapper>

=== dbarbier/privot/lib/test/external_code_threads.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE wrapper SYSTEM "wrapper.dtd">
<!-- author : dutka -->
<!-- date   : 2008-06-26 13:50:17 +0200 (Thu, 26 Jun 2008) -->

<wrapper>
  <library>

    <!-- The path of the shared object -->
    <path>external_code_threads.so</path>



    <!-- This section describes all exchanges data between the wrapper and the platform -->
    <description>

      <!-- Those variables are substituted in the files above -->
      <!-- The order of variables is the order of the arguments of the function -->
      <variable-list>
        <!-- The definition of a variable -->
        <variable id="E" type="in" />
        <variable id="F" type="in" />
        <variable id="L" type="in" />
        <variable id="I" type="in" />
        <variable id="d" type="out" />
      </variable-list>


      <!-- The function that we try to execute through the wrapper -->
      <function provided="yes">external_code</function>

      <!-- the gradient is  defined  -->
      <gradient provided="no" />

      <!--  the hessian is  defined  -->
      <hessian provided="no" />

    </description>

  </library>

  <external-code>
    <!-- Those data are external to the platform (input files, etc.)-->
    <data>
    </data>

    <wrap-mode type="static-link">
      <in-data-transfer mode="arguments" />
      <out-data-transfer mode="arguments" />
    </wrap-mode>

    <command />

  </external-code>

</wrapper>

=== dbarbier/privot/lib/test/poutre_external_WIN32.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE wrapper SYSTEM "wrapper.dtd">
<!-- author : schueller -->
<!-- date   : 2011-11-03 17:54:29 +0100 (Thu, 03 Nov 2011) -->

<wrapper>
  <library>

    <!-- The path of the shared object -->
    <path>poutre.so</path>



    <!-- This section describes all exchanges data between the wrapper and the platform -->
    <description>

      <!-- Those variables are substituted in the files above -->
      <!-- The order of variables is the order of the arguments of the function -->
      <variable-list>

        <!-- The definition of a variable -->
        <variable id="E" type="in">
          <comment>meanYoungModulus</comment>
          <unit>Pascal</unit>
          <regexp>E=.*</regexp>
          <format>E=%G</format>
        </variable>

        <!-- The definition of a variable -->
        <variable id="F" type="in">
          <comment>LoadForce</comment>
          <unit>Newton</unit>
          <regexp>F=.*</regexp>
          <format>F=%G</format>
        </variable>
      
        <!-- The definition of a variable -->
        <variable id="L" type="in">
          <comment>BeamLength</comment>
          <unit>Meter</unit>
          <regexp>L=.*</regexp>
          <format>L=%G</format>
        </variable>
      
        <!-- The definition of a variable -->
        <variable id="I" type="in">
          <comment>SectionInertia</comment>
          <unit>Meter^4</unit>
          <regexp>I=.*</regexp>
          <format>I=%G</format>
        </variable>

        <!-- The definition of a variable -->
        <variable id="d" type="out">
          <comment>Deviation</comment>
          <unit>Meter</unit>
          <regexp>d=(.*)</regexp>
          <format>\1</format>
        </variable>

      </variable-list>
      


      <!-- The function that we try to execute through the wrapper -->
      <function provided="yes">compute_deviation</function>

      <!-- the gradient is  defined  -->
      <gradient provided="yes">compute_deviation</gradient>

      <!--  the hessian is  defined  -->
      <hessian provided="yes">compute_deviation</hessian>

    </description>


  </library>

  <external-code>
    <!-- Those data are external to the platform (input files, etc.)-->
    <data>
      <!-- An input file -->
      <file id="file-1" type="in">
	<name>StdIn</name>
	<path>poutre_external_infile1</path>
	<subst>E,F</subst>
      </file>

      <!-- An input file -->
      <file id="file-2" type="in">
	<name>StdIn</name>
	<path>poutre_external_infile2</path>
	<subst>L,I</subst>
      </file>

      <!-- An output file -->
      <file id="file-3" type="out">
	<name>StdOut</name>
	<path>poutre_external_outfile</path>
	<subst>d</subst>
      </file>
    </data>

    <wrap-mode type="fork" state="shared">
      <in-data-transfer mode="arguments" />
      <out-data-transfer mode="arguments" />
    </wrap-mode>

    <command>poutre_files.bat</command>

  </external-code>

</wrapper>

=== dbarbier/privot/lib/test/TestIdentity.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE wrapper SYSTEM "wrapper.dtd">
<wrapper>
  <library>
    <path>TestIdentity.so</path>
    <description>
      <variable-list>
        <variable id="x1" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x2" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x3" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="x4" type="in">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="y1" type="out">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="y2" type="out">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="y3" type="out">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
        <variable id="y4" type="out">
          <comment>Automatically generated</comment>
          <unit>None</unit>
          <regexp>None</regexp>
          <format>None</format>
        </variable>
      </variable-list>
      <function provided="yes">TestIdentity</function>
      <gradient provided="yes">TestIdentity</gradient>
      <hessian provided="yes">TestIdentity</hessian>
    </description>
  </library>
  <external-code>
    <data>
    </data>
    <wrap-mode type="static-link">
      <in-data-transfer mode="arguments" />
      <out-data-transfer mode="arguments" />
    </wrap-mode>
    <command>
    </command>
  </external-code>
 </wrapper>
