=== dbarbier/privot/lib/src/Base/Func/wrapper.dtd
<?xml encoding="ISO-8859-1"?>

<!-- author : schueller -->
<!-- date   : 2011-06-01 17:59:24 +0200 (Wed, 01 Jun 2011) -->

<!ELEMENT wrapper           (library,external-code) >
<!ELEMENT library           (path,description) >
<!ELEMENT description       (variable-list,function,gradient,hessian) >
<!ELEMENT external-code     (data?,wrap-mode,command,user-prefix?) >
<!ELEMENT data              (file*,framework?) >
<!ELEMENT file              (name?,path,subst?) >
<!ELEMENT framework         (study-id?,study-case?,component-name?) >
<!ELEMENT variable-list     (variable*) >
<!ELEMENT variable          (comment?,unit?,regexp?,format?) >
<!ELEMENT function          (#PCDATA) >
<!ELEMENT gradient          (#PCDATA) >
<!ELEMENT hessian           (#PCDATA) >
<!ELEMENT name              (#PCDATA) >
<!ELEMENT path              (#PCDATA) >
<!ELEMENT subst             (#PCDATA) >
<!ELEMENT regexp            (#PCDATA) >
<!ELEMENT format            (#PCDATA) >
<!ELEMENT unit              (#PCDATA) >
<!ELEMENT comment           (#PCDATA) >
<!ELEMENT study-id          (#PCDATA) >
<!ELEMENT study-case        (#PCDATA) >
<!ELEMENT user-prefix       (#PCDATA) >
<!ELEMENT component-name    (#PCDATA) >
<!ELEMENT wrap-mode         (in-data-transfer,out-data-transfer) >
<!ELEMENT command           (#PCDATA) >
<!ELEMENT in-data-transfer  (#PCDATA) >
<!ELEMENT out-data-transfer (#PCDATA) >


<!ATTLIST wrapper
version NMTOKEN #IMPLIED>

<!ATTLIST file
id ID #REQUIRED
type (in|out) #REQUIRED>

<!ATTLIST variable
id ID #REQUIRED
type (in|out) #REQUIRED
computed-gradient (yes|no) #IMPLIED>

<!ATTLIST wrap-mode
type (static-link|dynamic-link|fork) #REQUIRED
state (shared|specific) #IMPLIED>

<!ATTLIST in-data-transfer
mode (files|pipe|arguments|socket|corba) #REQUIRED>

<!ATTLIST out-data-transfer
mode (files|pipe|arguments|socket|corba) #REQUIRED>

<!ATTLIST function
provided (yes|no) #REQUIRED>

<!ATTLIST gradient
provided (yes|no) #REQUIRED>

<!ATTLIST hessian
provided (yes|no) #REQUIRED>

=== dbarbier/privot/lib/test/wrapper.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE wrapper SYSTEM "wrapper.dtd">
<!-- author : dutka -->
<!-- date   : 2007-08-01 16:47:51 +0200 (Wed, 01 Aug 2007) -->

<wrapper>
  <library>

    <!-- The path of the shared object -->
    <path>testwrapper_3.so</path>



    <!-- This section describes all exchanges data between the wrapper and the platform -->
    <description>



      <!-- Those variables are substituted in the files above -->
      <!-- The order of variables is the order of the arguments of the function -->
      <variable-list>

        <!-- The definition of a variable -->
        <variable id="F" type="in">
          <comment>May the force be with you</comment>
          <unit>Newton</unit>
          <regexp>F=.*</regexp>
          <format>F=%10.5g</format>
        </variable>

        <!-- The definition of a variable -->
        <variable id="L" type="in">
          <comment>How long are you ?</comment>
          <unit>Meter</unit>
          <regexp>L=[0-9]+\.[0-9]* *m</regexp>
          <format>L=%8.4f</format>
        </variable>
      </variable-list>
      


    <!-- The function that we try to execute through the wrapper -->
    <function provided="yes">fonction1</function>
    
    <!-- The gradient of the function is defined into the wrapper -->
    <gradient provided="yes">gradient1</gradient>
    
    <!-- But the hessian is NOT defined, so it does NOT appear in this file -->
    <hessian provided="no" />
    
  </description>
    
    
  </library>

  <external-code>
      <!-- Those data are external to the platform (input files, etc.)-->
      <data>

	<!-- An input file -->
        <file id="file-1" type="in">
          <name>StdIn</name>
          <path>./fort.5</path>
        </file>

	<!-- Another input file -->
        <file id="file-2" type="in">
          <name>StdTruc</name>
          <path>/tmp/fort.55</path>
        </file>

	<!-- An output file -->
        <file id="file-3" type="out">
          <name>StdOut</name>
          <path>/tmp/out/fort.6</path>
        </file>

      </data>

    <wrap-mode type="static-link">
      <in-data-transfer mode="arguments" />
      <out-data-transfer mode="arguments" />
    </wrap-mode>

    <command>
    </command>
  </external-code>

</wrapper>

=== dbarbier/privot/lib/test/minimal_wrapper.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE wrapper SYSTEM "wrapper.dtd">
<!-- author : dutka -->
<!-- date   : 2008-06-26 13:50:17 +0200 (Thu, 26 Jun 2008) -->

<wrapper>
  <library>

    <!-- The path of the shared object -->
    <path>minimal_wrapper.so</path>



    <!-- This section describes all exchanges data between the wrapper and the platform -->
    <description>

      <!-- The variables are declared in the exact order of the arguments of the function -->
      <variable-list>
        <variable id="x1" type="in" />
        <variable id="x2" type="in" />
        <variable id="y" type="out" />
      </variable-list>
      


      <!-- The function that we try to execute through the wrapper -->
      <function provided="yes">smallest</function>

      <!-- The gradient is NOT defined  -->
      <gradient provided="no" />

      <!-- The hessian is NOT defined  -->
      <hessian provided="no" />

    </description>


  </library>

  <external-code>
    <!-- Those data are external to the platform (input files, etc.)-->
    <data />

    <wrap-mode type="static-link" state="shared">
      <in-data-transfer mode="arguments" />
      <out-data-transfer mode="arguments" />
    </wrap-mode>

    <command />

  </external-code>

</wrapper>
